AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  EdgeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayFullAccess
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-images-Lambda-S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
                - s3:*
              Resource:
                - !Sub arn:aws:s3:::*

  OriginAccessId:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName}-OriginAccessId

  UriToS3KeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-UriToS3Key
      AutoPublishAlias: live
      CodeUri: src/UriToS3Key/
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 1
      Role: !GetAtt EdgeLambdaRole.Arn

  GetOrCreateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-GetOrCreateImage
      AutoPublishAlias: live
      CodeUri: src/GetOrCreateImage/
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Timeout: 30
      Role: !GetAtt EdgeLambdaRole.Arn

Outputs:
  UriToS3KeyFunction:
    Value: !Ref UriToS3KeyFunction
    Description: Lambda function for the Cloudfront viewer-request event.

  GetOrCreateImageFunction:
    Value: !Ref GetOrCreateImageFunction
    Description: Lambda function for the Cloudfront origin-response event.
